.PHONY: clean All

All:
	@echo "----------Building project:[ FunctionsChallenge - Debug ]----------"
	@cd "FunctionsChallenge" && "$(MAKE)" -f  "FunctionsChallenge.mk"
clean:
	@echo "----------Cleaning project:[ FunctionsChallenge - Debug ]----------"
	@cd "FunctionsChallenge" && "$(MAKE)" -f  "FunctionsChallenge.mk" clean
