.PHONY: clean All

All:
	@echo "----------Building project:[ SizeOfDataTypes - Debug ]----------"
	@cd "SizeOfDataTypes" && "$(MAKE)" -f  "SizeOfDataTypes.mk"
clean:
	@echo "----------Cleaning project:[ SizeOfDataTypes - Debug ]----------"
	@cd "SizeOfDataTypes" && "$(MAKE)" -f  "SizeOfDataTypes.mk" clean
