.PHONY: clean All

All:
	@echo "----------Building project:[ CalculateTakeHomePay - Debug ]----------"
	@cd "CalculateTakeHomePay" && "$(MAKE)" -f  "CalculateTakeHomePay.mk"
clean:
	@echo "----------Cleaning project:[ CalculateTakeHomePay - Debug ]----------"
	@cd "CalculateTakeHomePay" && "$(MAKE)" -f  "CalculateTakeHomePay.mk" clean
